---

#server
  - name: Atualiza o cache apt de nosso servidor
    apt: update_cache=yes cache_valid_time=3600
 
  - name: Instala os pacotes necessarios
    apt: name={{ item }} state=present
    with_items:
    - apache2
    - mysql-server
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb


#php
  - name: Instala as extensoes PHP necessarias
    apt: name={{ item }} state=present
    with_items:
    - php5-gd
    - libssh2-php

#mysql
  # nome do banco de dados da aplicacao
  wp_mysql_db: wordpress
  # login a ser criado para a aplicacao
  wp_mysql_user: wordpress
  # senha a ser atribuida para o login da aplicacao
  wp_mysql_password: wp_db_password

  - name: Cria o banco de dados para o WordPress
    mysql_db: name={{ wpS_mysql_db }} state=present
   
  - name: Cria um usuario de banco para o WordPress
    mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL

#wordpress
  - name: Baixa o WordPress
    get_url: 
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

  - name: Descompacta o WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

  - name: Atualiza o site Apache padrao
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
  regexp="(.)+DocumentRoot /var/www/html"
  line="DocumentRoot /var/www/wordpress"
  notify:
  - reinicia apache

  - name: Renomeia o arquivo de configuracao de exemplo
    command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

  - name: Atualiza a configuracao WordPress
  lineinfile:
  dest=/var/www/wordpress/wp-config.php
  regexp="{{ item.regexp }}"
  line="{{ item.line }}"
  with_items:
  - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}     
  - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}     
  - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}


